service: aws-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  endpointType: regional 

functions:
  register_node:
    handler: handlers/registration.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/register
          method: POST

  product_search:
    handler: handlers/productsearch.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/products-lis
          method: GET

  add_cart:
    handler: handlers/addcart.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/cart/add
          method: POST
  
  check-out:
    handler: handlers/checkout.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/checkout
          method: POST
  
  order-status:
    handler: handlers/order_status.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/orders/{order_id}/status
          method: GET
  
  user-profile:
    handler: handlers/user_profile.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/profile
          method: GET
        
  update-profile:
    handler: handlers/update_profile.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/profile
          method: PUT

  remove-cart:
    handler: handlers/remove_cart.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/cart/remove
          method: DELETE

  orders:
    handler: handlers/orders.handler
    role: arn:aws:iam::029789602047:role/Lambda-dynamodb-role
    events:
      - http:
          path: api/orders
          method: GET

